Show user statistics in an API call
kevinpapst/kimai2 pull request #2346
Opened 2021-02-13 21:42 UTC by ZeiP

## Description
Adds an API call for user statistics. It's probably not acceptable as-is, but this worked for me so it's at least a start.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [X] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

Fixes #2176.

2021-02-14 20:46 UTC, kevinpapst requested changes
Thanks!
Tests are missing and I think it might be good to allow to pass in the user ID.
What do you say?

2021-02-14 20:46 UTC, kevinpapst commented on src/API/ReportController.php
> +     *          @SWG\Items(ref="#/definitions/ActivityCollection")
wrong result type

2021-02-14 20:46 UTC, kevinpapst commented on src/API/ReportController.php
> +        $currentUser = $this->getUser();
should be limited  by `$this->isGranted('view', $currentUser)`

2021-02-14 20:46 UTC, kevinpapst commented on src/API/ReportController.php
> +     * Returns stats.
Not the shortest documentation I have ever seen ... but almost 😁

2021-04-05 20:08 UTC, kevinpapst commented
Thank you for your PR and the invested time 👍 

Nevertheless, I am closing this PR unmerged for two reasons: 

- I don't want to include API endpoints for statistics
- Review feedback and failing tests ignored

This feature should be published as plugin.

2021-04-05 20:08 UTC, closed without merging

2021-04-05 20:10 UTC, ZeiP commented
Sorry, unfortunately I haven't had time to look into this. I'd be happy to fix the PR, but if it's not going to be merged then I'll just keep it in my local branch. I doubt publishing a separate plugin for a single API endpoint is useful.

2021-04-05 20:13 UTC, kevinpapst commented
I was working on a reporting plugin. If I manage to publish it (time is missing) I will send you a ping, then we can move this endpoint there.