feat: adds support for setting description by http params
kevinpapst/kimai2 pull request #2580
Opened 2021-05-21 08:54 UTC by tobybatch

## Description
A clear and concise description of what this pull request adds or changes.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [X] I verified that my code applies to the guidelines (`composer code-check`)
- [X] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [X] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

2021-05-21 08:55 UTC, tobybatch commented
@kevinpapst I'd like to add a test for this too, are there tests for the http param stuff? where? and I'll add one for this.

2021-05-21 10:42 UTC, kevinpapst requested changes

2021-05-21 10:42 UTC, kevinpapst commented on src/Controller/TimesheetAbstractController.php
> +            $description = $activityRepository->find($request->query->get('description'));
Copy & Paste

2021-05-21 10:44 UTC, kevinpapst commented
https://github.com/kevinpapst/kimai2/blob/master/tests/Controller/TimesheetControllerTest.php#L279

2021-05-21 10:56 UTC, tobybatch commented
And that's why I wanted the pointer to the tests :)

Thanks Kev.

2021-05-21 13:02 UTC, tobybatch commented
@kevinpapst I'm getting

```
failed to open stream: Too many open files
```

While running tests, my system limit is high but php seems to be choking it.

2021-05-21 13:09 UTC, kevinpapst commented
Either:
- Push and let GitHub actions do the work
- or simply execute only one test with `vendor/bin/phpunit tests/Controller/TimesheetControllerTest.php`

As I dropped SQLite support, please `cp phpunit.xml.dist phpunit.dist` and change to true `<env name="BOOTSTRAP_RESET_DATABASE" value="true"/>`.
You need to create a db and user first, commands can be copy & pasted from here: https://github.com/kevinpapst/kimai2/blob/master/phpunit.xml.dist#L19

2021-05-21 13:11 UTC, tobybatch commented
Yeah, I'd got the new SQL test DB settings, that was fine. I was just trying to run the whole test suite.

I'll just run my test. TYhanks

2021-05-24 08:15 UTC, tobybatch commented
@kevinpapst Tests added, changes made, linting linted. I've switch it from a draft to a real PR.

2021-05-31 14:04 UTC, kevinpapst commented
What do you need that for exactly?
Did you try to inject HTML for a XSS attack?

2021-06-23 07:32 UTC, tobybatch commented
Added a test to check html injection can't be done. 

I'm moving my browser extension (https://github.com/tobybatch/kimai-browser-plugin) to use tags rather than a custom method for storing relationship between projects/activities and github tickets. I don't think XSS is a vulnerability as a user must be logged in and the description text is correctly decoded.

2021-08-08 12:28 UTC, kevinpapst approved these changes
I was a bit worried about possible security issues, but there is no real difference between get and post params, so good to merge. Thanks @tobybatch 👍

2021-08-08 12:29 UTC, merged