Prevent bookings with same start / stop time
kevinpapst/kimai2 pull request #3304
Opened 2022-05-11 15:12 UTC by Wolfimschafspelz

## Description
- Makes it impossible to create bookings with the same start / stop time when unchecking a box in the system settings

![grafik](https://user-images.githubusercontent.com/24376183/167884292-cb812619-f5ea-451b-a045-abe308202083.png)

![grafik](https://user-images.githubusercontent.com/24376183/167884551-a77ba8e2-7e43-4b63-bcd1-6ff10aeb9087.png)

- closes #2342

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

2022-05-11 15:23 UTC, kevinpapst requested changes
Thank @Wolfimschafspelz 👍 

We need to add some missing translations, so the show up in Weblate for the translation to all other languages.

In `validators.en.xlf` the key `Duration cannot be zero.` with the same translations.

And your username suggests that you can add the German translations for the two new messages 😄 ?!?

2022-05-11 15:23 UTC, kevinpapst commented on src/Validator/Constraints/TimesheetZeroLengthValidator.php
> +            $this->context->buildViolation('The duration cannot be zero.')
```suggestion
            $this->context->buildViolation($constraint->message)
```

2022-05-11 15:23 UTC, kevinpapst commented on src/Validator/Constraints/TimesheetZeroLength.php
> +        self::ZERO_LENGTH_ERROR => 'The Duration can not be zero.',
```suggestion
        self::ZERO_LENGTH_ERROR => 'Duration cannot be zero.',
```

2022-05-11 15:23 UTC, kevinpapst commented on src/Validator/Constraints/TimesheetZeroLength.php
> +    public $message = 'The Duration can not be zero.';
```suggestion
    public $message = 'Duration cannot be zero.';
```

2022-05-11 20:05 UTC, kevinpapst requested changes
Hey, after giving another thought, I'd like to see two more changes:
- replace "Length" with "Duration" in all places
- add a unit test for the validator

Edit: the last fixes were exactly what I had in mind, thank you 👍

2022-05-12 09:20 UTC, kevinpapst reviewed
There are some other issues in existing tests, due to the added configuration. I can solve them later on, if you don't find the solution.

2022-05-12 09:20 UTC, kevinpapst commented on tests/Validator/Constraints/TimesheetZeroDurationValidatorTest.php
> +        $timesheet = prepareTimesheet();
```suggestion
        $timesheet = $this->prepareTimesheet();
```

2022-05-12 09:20 UTC, kevinpapst commented on tests/Validator/Constraints/TimesheetZeroDurationValidatorTest.php
> +        $timesheet = prepareTimesheet();
```suggestion
        $this->validator = $this->createMyValidator(true);
        $this->validator->initialize($this->context);

        $timesheet = $this->prepareTimesheet();
```

2022-05-12 09:20 UTC, kevinpapst commented on tests/Validator/Constraints/TimesheetZeroDurationValidatorTest.php
> +        self::assertEmpty($this->context->getViolations());
```suggestion
        $this->assertNoViolation();
```

2022-05-12 15:08 UTC, kevinpapst commented
Please run `composer codestyle-fix` and `composer phpstan` before committing.

2022-05-12 21:20 UTC, Wolfimschafspelz commented
Hey,
There are one error and one failed test case in the integration tests remaining which I was unable to resolve.

2022-05-17 09:01 UTC, kevinpapst approved these changes
Looks good to me 👍  

Thank you @Wolfimschafspelz for being patient 😄

2022-05-17 09:12 UTC, merged